data:
  train_fid_list: "/home/grads/b/bhanu/ppg-vc/train.txt"
  dev_fid_list: "/home/grads/b/bhanu/ppg-vc/dev.txt"
  eval_fid_list: "/home/shaunxliu/data/vctk/fidlists/eval_fidlist.txt"
  arctic_ppg_dir: "/mnt/data2/bhanu/datasets/bfn_feats"
  arctic_f0_dir: "/mnt/data2/bhanu/datasets/f0"
  arctic_wav_dir: "/mnt/data2/bhanu/datasets/all_data_for_ac_vc"
  arctic_spk_dvec_dir: "/mnt/data2/bhanu/datasets/dvec/GE2E_spkEmbed_step_5805000"
  ppg_file_ext: "ling_feat.npy"
  f0_file_ext: "f0.npy"
  wav_file_ext: "wav"
  min_max_norm_mel: true
  mel_min: -12.0
  mel_max: 2.5 

hparas:
  batch_size: 5
  valid_step: 1000
  max_step: 1000000
  optimizer: 'Adam'
  lr: 0.001
  eps: 1.0e-8
  weight_decay: 1.0e-6
  lr_scheduler: 'warmup'   # "fixed", "warmup"

model_name: "bilstm"
model:
  input_size: 146    # 144 ppg-dim and 2 pitch 
  multi_spk: True
  use_spk_dvec: True  # for one-shot VC
  
  
